# Generated by Django 5.1.7 on 2025-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_parcelle_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='categorie',
            field=models.CharField(choices=[('Nue', 'Nue'), ('Residentiel', 'Residentiel'), ('Industriel', 'Industriel')], default='Nue', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
