# Generated by Django 5.1.7 on 2025-03-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_alter_parcelle_categorie_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='categorie',
            field=models.CharField(choices=[('Nue', 'Nue'), ('Industriel', 'Industriel'), ('Residentiel', 'Residentiel')], default='Nue', max_length=50),
        ),
    ]
