# Generated by Django 5.1.7 on 2025-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_alter_parcelle_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='categorie',
            field=models.CharField(choices=[('Residentiel', 'Residentiel'), ('Nue', 'Nue'), ('Industriel', 'Industriel')], default='Nue', max_length=50),
        ),
    ]
