# Generated by Django 5.1.7 on 2025-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_alter_parcelle_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='categorie',
            field=models.CharField(choices=[('Nue', 'Nue'), ('Industriel', 'Industriel'), ('Residentiel', 'Residentiel')], default='Nue', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
